
demo.datasource:
  url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true
  username: postgres
  password: 46e7v6bbn7y
  driver-class-name: org.postgresql.Driver

spring:
  flyway:
    baseline-on-migrate: true