
spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy


demo.datasource:
  url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true
  username: postgres
  password: 46e7v6bbn7y
  driver-class-name: org.postgresql.Driver


messages:
  generated:
    length: 10
    qty: 10
  to-send:
    qty: 3
    timeout:
      receive-checkout: 1
